-- MySQL Script generated by MySQL Workbench
-- Mon Feb 20 11:14:03 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema greenhill_localhost
-- -----------------------------------------------------

CREATE SCHEMA IF NOT EXISTS `greenhill_localhost` DEFAULT CHARACTER SET utf8 ;
USE `greenhill_localhost` ;

-- -----------------------------------------------------
-- Table `greenhill_localhost`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Users` (
  `user_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NULL,
  `username` VARCHAR(25) NOT NULL,
  `invitation_code` VARCHAR(10) NULL,
  `email` VARCHAR(320) NOT NULL,
  `phone_number` VARCHAR(20) NULL,
  `password` VARCHAR(100) NOT NULL,
  `user_type` ENUM('admin', 'employee', 'advisor') NOT NULL,
  `is_financial_advisor` TINYINT(1) NOT NULL DEFAULT 0,
  `picture` BLOB NULL,
  `active` TINYINT(1) NULL,
  `last_update` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `date_created` DATE NOT NULL DEFAULT (CURRENT_DATE),
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `greenhill_localhost`.`Referrals`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Referrals` (
  `referral_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `referrer_id` INT UNSIGNED NOT NULL,
  `referred_email` VARCHAR(320) NOT NULL,
  `referral_code` VARCHAR(10) NOT NULL,
  `status` ENUM('pending', 'accepted', 'expired') NOT NULL,
  `date_created` DATE NOT NULL DEFAULT (CURRENT_DATE),
  `expiration_date` TIMESTAMP(6) NULL,
  `is_used` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`referral_id`),
  UNIQUE INDEX `referral_code_UNIQUE` (`referral_code` ASC) VISIBLE,
  CONSTRAINT `referrer_id_referrals`
    FOREIGN KEY (`referrer_id`)
    REFERENCES `greenhill_localhost`.`Users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `greenhill_localhost`.`Stocks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Stocks` (
  `stock_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ticker` VARCHAR(5) NOT NULL,
  `description` TEXT NULL,
  `dividend` DECIMAL(5,2) NULL,
  `payment_freq` INT NULL,
  `last_update` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`stock_id`),
  UNIQUE INDEX `stock_id_UNIQUE` (`stock_id` ASC) VISIBLE,
  UNIQUE INDEX `ticker_UNIQUE` (`ticker` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `greenhill_localhost`.`GameInfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GameInfo` (
  `game_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NULL,
  `starting_cash` DECIMAL(5,2) NULL,
  `start_date` DATETIME NOT NULL,
  `end_date` DATETIME NOT NULL,
  `last_update` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`game_id`),
  UNIQUE INDEX `game_id_UNIQUE` (`game_id` ASC) VISIBLE,
  CONSTRAINT `user_id_gameinfo`
    FOREIGN KEY (`user_id`)
    REFERENCES `greenhill_localhost`.`Users` (`user_id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `greenhill_localhost`.`Portfolios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Portfolios` (
  `portfolio_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `portfolio_name` VARCHAR(45) NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  `game_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`portfolio_id`),
  CONSTRAINT `user_id_portfolios`
    FOREIGN KEY (`user_id`)
    REFERENCES `greenhill_localhost`.`Users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `game_id_portfolios`
    FOREIGN KEY (`game_id`)
    REFERENCES `greenhill_localhost`.`GameInfo` (`game_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `greenhill_localhost`.`PortfolioStock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PortfolioStock` (
  `portfolio_id` INT UNSIGNED NOT NULL,
  `stock_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`portfolio_id`, `stock_id`),
  INDEX `stock_id_idx` (`stock_id` ASC) VISIBLE,
  CONSTRAINT `portfolio_id`
    FOREIGN KEY (`portfolio_id`)
    REFERENCES `greenhill_localhost`.`Portfolios` (`portfolio_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `stock_id_portfoliostock`
    FOREIGN KEY (`stock_id`)
    REFERENCES `greenhill_localhost`.`Stocks` (`stock_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `greenhill_localhost`.`StockHistory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StockHistory` (
  `record_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `stock_id` INT UNSIGNED NOT NULL,
  `price` DECIMAL(5,2) NULL,
  `cusip` VARCHAR(10) NOT NULL,
  `timestamp` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`record_id`),
  UNIQUE INDEX `stock_id_timestamp_UNIQUE` (`stock_id`, `timestamp`) VISIBLE,
  CONSTRAINT `stock_id_stockhistory`
    FOREIGN KEY (`stock_id`)
    REFERENCES `greenhill_localhost`.`Stocks` (`stock_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `greenhill_localhost`.`FAQ`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FAQ` (
  `faq_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `question` VARCHAR(255) NOT NULL,
  `answer` TEXT NOT NULL,
  `date_created` DATE NOT NULL,
  PRIMARY KEY (`faq_id`)
) ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
